spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: "jdbc:postgresql://${ALBAM_MATE_DB_HOST}:${ALBAM_MATE_DB_PORT}/${ALBAM_MATE_DB_NAME}?sslmode=disable&ApplicationName=albam-mate"
    username: ${ALBAM_MATE_DB_USER}
    password: ${ALBAM_MATE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'
      maximum-pool-size: ${ALBAM_MATE_DB_MAXIMUM_POOL_SIZE:8}
      minimum-idle: ${ALBAM_MATE_DB_MINIMUM_IDLE:2}
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/vendor-migration/postgresql
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: 30s
  data:
    redis:
      host: ${ALBAM_MATE_REDIS_HOST}
      port: ${ALBAM_MATE_REDIS_PORT:6379}

server:
  forward-headers-strategy: framework
  shutdown: graceful

app:
  security:
    cookie:
      secure: true
  redis:
    host: ${ALBAM_MATE_REDIS_HOST}
    port: ${ALBAM_MATE_REDIS_PORT:6379}
  chat:
    websocket:
      allowed-origin: ${ALBAM_MATE_CHAT_WEBSOCKET_ALLOWED_ORIGIN:}
