ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT ck_users_password_hash_requires_email
    CHECK (password_hash IS NULL OR email IS NOT NULL);

CREATE TABLE social_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_social_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT ck_social_accounts_provider
        CHECK (provider IN ('GOOGLE', 'NAVER', 'KAKAO')),
    CONSTRAINT uq_social_accounts_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT uq_social_accounts_user_provider UNIQUE (user_id, provider)
);
