CREATE TABLE game_mechanisms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bgg_mechanism_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    name_ko VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    featured_order SMALLINT,
    is_public BOOLEAN NOT NULL DEFAULT false,
    source_reference VARCHAR(500) NOT NULL,
    reviewed_by VARCHAR(100),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_game_mechanisms_bgg_mechanism_id UNIQUE (bgg_mechanism_id),
    CONSTRAINT uq_game_mechanisms_code UNIQUE (code),
    CONSTRAINT uq_game_mechanisms_featured_order UNIQUE (featured_order),
    CONSTRAINT ck_game_mechanisms_featured_order
        CHECK (featured_order IS NULL OR featured_order BETWEEN 1 AND 8),
    CONSTRAINT ck_game_mechanisms_public_reviewed
        CHECK (NOT is_public OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL))
);

CREATE TABLE game_mechanism_relations (
    game_id BIGINT NOT NULL,
    mechanism_id BIGINT NOT NULL,
    PRIMARY KEY (game_id, mechanism_id),
    CONSTRAINT fk_game_mechanism_relations_game
        FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_mechanism_relations_mechanism
        FOREIGN KEY (mechanism_id) REFERENCES game_mechanisms (id) ON DELETE CASCADE
);

CREATE INDEX idx_game_mechanism_relations_mechanism_game
    ON game_mechanism_relations (mechanism_id, game_id);
