CREATE TABLE user_played_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_played_games_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT fk_user_played_games_game
        FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE NO ACTION,
    CONSTRAINT uq_user_played_games_user_game UNIQUE (user_id, game_id)
);
