CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bgg_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    english_name VARCHAR(255) NOT NULL,
    alias VARCHAR(255),
    image_url VARCHAR(500),
    supported_player_count VARCHAR(50) NOT NULL,
    tag VARCHAR(30) NOT NULL,
    estimated_play_time VARCHAR(50) NOT NULL,
    complexity DECIMAL(3, 2),
    description TEXT NOT NULL,
    detail_description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_games_bgg_id UNIQUE (bgg_id)
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT,
    host_user_id BIGINT NOT NULL,
    room_type VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    experience_level VARCHAR(30) NOT NULL,
    is_rulemaster_led BOOLEAN NOT NULL,
    region VARCHAR(50) NOT NULL DEFAULT '홍대',
    capacity INT NOT NULL,
    active_participant_count INT NOT NULL DEFAULT 0,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    place VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_rooms_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT fk_rooms_host_user FOREIGN KEY (host_user_id) REFERENCES users (id),
    CONSTRAINT ck_rooms_room_type
        CHECK (room_type IN ('GAME_FOCUSED', 'PERSON_FOCUSED')),
    CONSTRAINT ck_rooms_experience_level
        CHECK (experience_level IN ('ALL_LEVELS', 'BEGINNER_WELCOME', 'EXPERIENCED_PREFERRED')),
    CONSTRAINT ck_rooms_status
        CHECK (status IN ('RECRUITING', 'CLOSED', 'CANCELED', 'FINISHED')),
    CONSTRAINT ck_rooms_game_required
        CHECK (room_type <> 'GAME_FOCUSED' OR game_id IS NOT NULL),
    CONSTRAINT ck_rooms_capacity CHECK (capacity BETWEEN 1 AND 10),
    CONSTRAINT ck_rooms_active_participant_count
        CHECK (active_participant_count BETWEEN 0 AND capacity)
);

CREATE TABLE participations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    canceled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_participations_room FOREIGN KEY (room_id) REFERENCES rooms (id),
    CONSTRAINT fk_participations_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_participations_room_user UNIQUE (room_id, user_id),
    CONSTRAINT ck_participations_status
        CHECK (status IN ('ACTIVE', 'CANCELED')),
    CONSTRAINT ck_participations_status_canceled_at
        CHECK ((status = 'ACTIVE' AND canceled_at IS NULL)
            OR (status = 'CANCELED' AND canceled_at IS NOT NULL))
);
