create table game_categories (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    name_ko varchar(100) not null,
    name_en varchar(100) not null,
    bgg_subdomain varchar(64) not null unique,
    display_order integer not null unique check (display_order between 1 and 8),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table game_category_relations (
    game_id bigint not null references games(id) on delete cascade,
    category_id bigint not null references game_categories(id) on delete cascade,
    primary key (game_id, category_id)
);
create index ix_game_category_relations_category_id on game_category_relations(category_id);

create table game_themes (
    id bigint generated by default as identity primary key,
    bgg_theme_id bigint not null unique,
    code varchar(64) not null unique,
    name_ko varchar(100) not null,
    name_en varchar(100) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table game_theme_relations (
    game_id bigint not null references games(id) on delete cascade,
    theme_id bigint not null references game_themes(id) on delete cascade,
    primary key (game_id, theme_id)
);
create index ix_game_theme_relations_theme_id on game_theme_relations(theme_id);

create table game_player_preferences (
    game_id bigint not null references games(id) on delete cascade,
    player_count integer not null check (player_count > 0),
    is_recommended boolean not null,
    is_best boolean not null,
    primary key (game_id, player_count),
    constraint ck_game_player_preferences_best_requires_recommended
        check (not is_best or is_recommended)
);
