CREATE TABLE match_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    min_party_size SMALLINT NOT NULL,
    max_party_size SMALLINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    queued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    priority_since TIMESTAMP WITH TIME ZONE NOT NULL,
    proposed_at TIMESTAMP WITH TIME ZONE,
    matched_at TIMESTAMP WITH TIME ZONE,
    purge_after TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_requests_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_match_requests_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT ck_match_requests_party_size CHECK (min_party_size > 0 AND min_party_size <= max_party_size),
    CONSTRAINT ck_match_requests_status CHECK (status IN ('WAITING', 'PROPOSED', 'PAUSED', 'MATCHED', 'CANCELED')),
    CONSTRAINT uq_match_requests_id_user UNIQUE (id, user_id)
);

CREATE TABLE match_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    party_size SMALLINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    respond_by TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    purge_after TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_proposals_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT ck_match_proposals_status CHECK (status IN ('OPEN', 'CONFIRMED', 'DECLINED', 'EXPIRED', 'CANCELED')),
    CONSTRAINT ck_match_proposals_party_size CHECK (party_size > 0)
);

CREATE TABLE match_proposal_members (
    proposal_id BIGINT NOT NULL,
    match_request_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    response_status VARCHAR(20) NOT NULL,
    responded_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_match_proposal_members PRIMARY KEY (proposal_id, match_request_id),
    CONSTRAINT fk_match_proposal_members_proposal FOREIGN KEY (proposal_id) REFERENCES match_proposals (id) ON DELETE CASCADE,
    CONSTRAINT fk_match_proposal_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_match_proposal_members_request_owner FOREIGN KEY (match_request_id, user_id) REFERENCES match_requests (id, user_id) ON DELETE CASCADE,
    CONSTRAINT uq_match_proposal_members_user UNIQUE (proposal_id, user_id),
    CONSTRAINT ck_match_proposal_members_response_status CHECK (response_status IN ('PENDING', 'ACCEPTED', 'REQUEUED', 'CANCELED', 'EXPIRED')),
    CONSTRAINT ck_match_proposal_members_response_lifecycle CHECK (
        (response_status IN ('PENDING', 'EXPIRED') AND responded_at IS NULL)
        OR (response_status IN ('ACCEPTED', 'REQUEUED', 'CANCELED') AND responded_at IS NOT NULL)
    )
);

CREATE TABLE match_parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT,
    game_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    preparing_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    chat_opened_at TIMESTAMP WITH TIME ZONE,
    closes_at TIMESTAMP WITH TIME ZONE,
    closed_at TIMESTAMP WITH TIME ZONE,
    purge_after TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_parties_proposal FOREIGN KEY (proposal_id) REFERENCES match_proposals (id) ON DELETE SET NULL,
    CONSTRAINT fk_match_parties_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT ck_match_parties_status CHECK (status IN ('PREPARING', 'ACTIVE', 'CLOSED')),
    CONSTRAINT ck_match_parties_lifecycle_common CHECK (
        (status = 'PREPARING')
        OR (status = 'ACTIVE' AND chat_opened_at IS NOT NULL AND closes_at IS NOT NULL)
        OR (status = 'CLOSED' AND closed_at IS NOT NULL AND purge_after IS NOT NULL)
    )
);

CREATE TABLE match_party_participants (
    party_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    participant_ref UUID NOT NULL,
    left_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_match_party_participants PRIMARY KEY (party_id, user_id),
    CONSTRAINT fk_match_party_participants_party FOREIGN KEY (party_id) REFERENCES match_parties (id) ON DELETE CASCADE,
    CONSTRAINT fk_match_party_participants_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_match_party_participants_ref UNIQUE (party_id, participant_ref)
);

CREATE TABLE match_chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_chat_rooms_party FOREIGN KEY (party_id) REFERENCES match_parties (id) ON DELETE RESTRICT,
    CONSTRAINT uq_match_chat_rooms_party UNIQUE (party_id)
);

CREATE TABLE match_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_chat_room_id BIGINT NOT NULL,
    sender_user_id BIGINT,
    message_type VARCHAR(20) NOT NULL,
    client_message_id VARCHAR(100),
    system_event_key VARCHAR(30),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_chat_messages_room FOREIGN KEY (match_chat_room_id) REFERENCES match_chat_rooms (id) ON DELETE CASCADE,
    CONSTRAINT fk_match_chat_messages_sender FOREIGN KEY (sender_user_id) REFERENCES users (id),
    CONSTRAINT ck_match_chat_messages_kind CHECK (
        (message_type = 'USER' AND sender_user_id IS NOT NULL AND client_message_id IS NOT NULL AND system_event_key IS NULL)
        OR (message_type = 'SYSTEM' AND sender_user_id IS NULL AND client_message_id IS NULL AND system_event_key IN ('CHAT_OPENED', 'CLOSES_IN_ONE_HOUR'))
    )
);

CREATE TABLE match_idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    operation VARCHAR(30) NOT NULL,
    payload_fingerprint VARCHAR(255) NOT NULL,
    result_entity_type VARCHAR(30),
    result_entity_id BIGINT,
    result_state VARCHAR(30),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_idempotency_records_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_match_idempotency_records_user_key UNIQUE (user_id, idempotency_key),
    CONSTRAINT ck_match_idempotency_operation CHECK (operation IN ('MATCH_REQUEST_CREATE', 'MATCH_PROPOSAL_RESPONSE'))
);
CREATE INDEX idx_match_idempotency_records_expiry
    ON match_idempotency_records (expires_at, id);

CREATE TABLE match_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id BIGINT NOT NULL,
    blocked_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_blocks_blocker FOREIGN KEY (blocker_user_id) REFERENCES users (id),
    CONSTRAINT fk_match_blocks_blocked FOREIGN KEY (blocked_user_id) REFERENCES users (id),
    CONSTRAINT ck_match_blocks_not_self CHECK (blocker_user_id <> blocked_user_id),
    CONSTRAINT uq_match_blocks_direction UNIQUE (blocker_user_id, blocked_user_id)
);
CREATE INDEX idx_match_blocks_blocked_blocker
    ON match_blocks (blocked_user_id, blocker_user_id);

CREATE TABLE match_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    reported_user_id BIGINT NOT NULL,
    reason VARCHAR(30) NOT NULL,
    reported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    purge_after TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_match_reports_reporter FOREIGN KEY (reporter_user_id) REFERENCES users (id),
    CONSTRAINT fk_match_reports_reported FOREIGN KEY (reported_user_id) REFERENCES users (id),
    CONSTRAINT ck_match_reports_reason CHECK (reason IN ('ABUSE_OR_HARASSMENT', 'HATE_OR_DISCRIMINATION', 'SEXUAL_CONTENT', 'SPAM_OR_SCAM', 'OTHER_RULE_VIOLATION')),
    CONSTRAINT ck_match_reports_not_self CHECK (reporter_user_id <> reported_user_id),
    CONSTRAINT uq_match_reports_reporter_reported UNIQUE (reporter_user_id, reported_user_id)
);
CREATE INDEX idx_match_reports_purge_after
    ON match_reports (purge_after, id);
