CREATE TABLE assistant_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, draft_version BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL, room_type VARCHAR(20) NOT NULL, title VARCHAR(100) NOT NULL,
    description VARCHAR(255), game_id BIGINT, experience_level VARCHAR(30) NOT NULL,
    is_rulemaster_led BOOLEAN NOT NULL, region VARCHAR(50) NOT NULL DEFAULT '홍대', capacity INT NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL, place VARCHAR(100), expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE, room_id BIGINT, chat_room_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_assistant_drafts_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_assistant_drafts_game FOREIGN KEY (game_id) REFERENCES games(id),
    CONSTRAINT fk_assistant_drafts_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_assistant_drafts_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id),
    CONSTRAINT ck_assistant_drafts_status CHECK (status IN ('ACTIVE', 'CONFIRMED', 'DISCARDED')),
    CONSTRAINT ck_assistant_drafts_room_type CHECK (room_type IN ('GAME_FOCUSED', 'PERSON_FOCUSED')),
    CONSTRAINT ck_assistant_drafts_experience_level CHECK (experience_level IN ('ALL_LEVELS', 'BEGINNER_WELCOME', 'EXPERIENCED_PREFERRED')),
    CONSTRAINT ck_assistant_drafts_region CHECK (region IN ('홍대', '강남', '건대', '잠실')),
    CONSTRAINT ck_assistant_drafts_capacity CHECK (capacity BETWEEN 1 AND 10),
    CONSTRAINT ck_assistant_drafts_game CHECK (room_type <> 'GAME_FOCUSED' OR game_id IS NOT NULL),
    CONSTRAINT ck_assistant_drafts_place_before_confirm CHECK (status <> 'CONFIRMED' OR place IS NOT NULL),
    CONSTRAINT ck_assistant_drafts_result CHECK (
        (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND room_id IS NOT NULL AND chat_room_id IS NOT NULL)
        OR (status <> 'CONFIRMED' AND confirmed_at IS NULL AND room_id IS NULL AND chat_room_id IS NULL)
    )
);

ALTER TABLE rooms ADD CONSTRAINT ck_rooms_region CHECK (region IN ('홍대', '강남', '건대', '잠실'));

CREATE TABLE assistant_idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, draft_id BIGINT NOT NULL, operation VARCHAR(30) NOT NULL,
    key_hash CHAR(64) NOT NULL, draft_version BIGINT NOT NULL, status VARCHAR(20) NOT NULL,
    room_id BIGINT, chat_room_id BIGINT, confirmed_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_assistant_idempotency_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_assistant_idempotency_draft FOREIGN KEY (draft_id) REFERENCES assistant_drafts(id),
    CONSTRAINT fk_assistant_idempotency_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_assistant_idempotency_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id),
    CONSTRAINT ck_assistant_idempotency_operation CHECK (operation = 'DRAFT_CONFIRM'),
    CONSTRAINT ck_assistant_idempotency_status CHECK (status IN ('PENDING', 'CONFIRMED')),
    CONSTRAINT uq_assistant_idempotency_draft_operation UNIQUE (user_id, draft_id, operation),
    CONSTRAINT uq_assistant_idempotency_user_key UNIQUE (user_id, key_hash)
);

CREATE INDEX idx_assistant_idempotency_expiry ON assistant_idempotency_records (expires_at, id);
