CREATE TABLE notification_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(30) NOT NULL,
    room_id BIGINT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    available_at TIMESTAMP WITH TIME ZONE,
    failure_count INT NOT NULL DEFAULT 0,
    total_failure_count INT NOT NULL DEFAULT 0,
    last_failure_code VARCHAR(50),
    last_failed_at TIMESTAMP WITH TIME ZONE,
    last_failure_class VARCHAR(255),
    last_failure_message VARCHAR(500),
    reprocess_count INT NOT NULL DEFAULT 0,
    last_reprocessed_at TIMESTAMP WITH TIME ZONE,
    last_reprocess_reason VARCHAR(500),
    processed_at TIMESTAMP WITH TIME ZONE,
    discarded_at TIMESTAMP WITH TIME ZONE,
    discard_reason VARCHAR(500),
    cleanup_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_notification_outbox_events_room
        FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE NO ACTION,
    CONSTRAINT ck_notification_outbox_events_event_type
        CHECK (event_type IN ('PARTICIPATION_JOINED', 'PARTICIPATION_CANCELED', 'ROOM_CANCELED')),
    CONSTRAINT ck_notification_outbox_events_status
        CHECK (status IN ('PENDING', 'RETRY_WAIT', 'PROCESSED', 'FAILED', 'DISCARDED')),
    CONSTRAINT ck_notification_outbox_events_failure_counts
        CHECK (failure_count BETWEEN 0 AND 5
            AND total_failure_count >= failure_count
            AND reprocess_count >= 0),
    CONSTRAINT ck_notification_outbox_events_available_at_status
        CHECK ((status IN ('PENDING', 'RETRY_WAIT')) = (available_at IS NOT NULL)),
    CONSTRAINT ck_notification_outbox_events_failure_details
        CHECK ((total_failure_count = 0
                AND last_failure_code IS NULL
                AND last_failed_at IS NULL
                AND last_failure_class IS NULL
                AND last_failure_message IS NULL)
            OR (total_failure_count > 0
                AND last_failure_code IS NOT NULL AND btrim(last_failure_code) <> ''
                AND last_failed_at IS NOT NULL
                AND last_failure_class IS NOT NULL AND btrim(last_failure_class) <> ''
                AND last_failure_message IS NOT NULL AND btrim(last_failure_message) <> '')),
    CONSTRAINT ck_notification_outbox_events_reprocess_details
        CHECK ((reprocess_count = 0
                AND last_reprocessed_at IS NULL
                AND last_reprocess_reason IS NULL)
            OR (reprocess_count > 0
                AND last_reprocessed_at IS NOT NULL
                AND last_reprocess_reason IS NOT NULL AND btrim(last_reprocess_reason) <> '')),
    CONSTRAINT ck_notification_outbox_events_pending
        CHECK (status <> 'PENDING'
            OR (available_at = recorded_at
                AND failure_count = 0
                AND total_failure_count = 0
                AND reprocess_count = 0)),
    CONSTRAINT ck_notification_outbox_events_retry_wait
        CHECK (status <> 'RETRY_WAIT' OR failure_count > 0 OR reprocess_count > 0),
    CONSTRAINT ck_notification_outbox_events_failed_or_discarded_failure
        CHECK (status NOT IN ('FAILED', 'DISCARDED') OR total_failure_count > 0),
	CONSTRAINT ck_notification_outbox_events_processed
		CHECK (status <> 'PROCESSED'
			OR (processed_at IS NOT NULL
				AND cleanup_at IS NOT NULL
				AND cleanup_at = processed_at + INTERVAL '30' DAY
                AND discarded_at IS NULL
                AND discard_reason IS NULL)),
	CONSTRAINT ck_notification_outbox_events_discarded
		CHECK (status <> 'DISCARDED'
			OR (discarded_at IS NOT NULL
				AND discard_reason IS NOT NULL AND btrim(discard_reason) <> ''
				AND cleanup_at IS NOT NULL
				AND cleanup_at = discarded_at + INTERVAL '30' DAY
                AND processed_at IS NULL)),
    CONSTRAINT ck_notification_outbox_events_incomplete
        CHECK (status NOT IN ('PENDING', 'RETRY_WAIT', 'FAILED')
            OR (processed_at IS NULL
                AND discarded_at IS NULL
                AND discard_reason IS NULL
                AND cleanup_at IS NULL))
);

CREATE TABLE notification_outbox_recipients (
    outbox_event_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    PRIMARY KEY (outbox_event_id, recipient_user_id),
    CONSTRAINT fk_notification_outbox_recipients_outbox_event
        FOREIGN KEY (outbox_event_id) REFERENCES notification_outbox_events (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_outbox_recipients_user
        FOREIGN KEY (recipient_user_id) REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_notifications_source_event_recipient UNIQUE (source_event_id, recipient_user_id),
    CONSTRAINT fk_notifications_recipient_user
        FOREIGN KEY (recipient_user_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT fk_notifications_room
        FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE NO ACTION,
    CONSTRAINT ck_notifications_type
        CHECK (type IN ('PARTICIPANT_JOINED', 'PARTICIPANT_CANCELED', 'ROOM_CANCELED')),
    CONSTRAINT ck_notifications_read_at
        CHECK (read_at IS NULL OR read_at >= recorded_at),
    CONSTRAINT ck_notifications_expires_at
        CHECK (expires_at = created_at + INTERVAL '90' DAY)
);

CREATE INDEX idx_notifications_recipient_created
    ON notifications (recipient_user_id, created_at DESC, id DESC);

CREATE INDEX idx_notifications_expiry
    ON notifications (expires_at, id);
