CREATE TABLE chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    purge_after TIMESTAMP WITH TIME ZONE,
    messages_purged_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_rooms_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE NO ACTION,
    CONSTRAINT uq_chat_rooms_room UNIQUE (room_id),
    CONSTRAINT ck_chat_rooms_purge_completion
        CHECK (messages_purged_at IS NULL OR purge_after IS NOT NULL)
);

INSERT INTO chat_rooms (room_id, purge_after, messages_purged_at, created_at, updated_at)
SELECT
    rooms.id,
    CASE
        WHEN rooms.status IN ('CANCELED', 'FINISHED') THEN backfill_boundary.initialized_at
        ELSE NULL
    END,
    CASE
        WHEN rooms.status IN ('CANCELED', 'FINISHED') THEN backfill_boundary.initialized_at
        ELSE NULL
    END,
    backfill_boundary.initialized_at,
    backfill_boundary.initialized_at
FROM rooms
CROSS JOIN (SELECT CURRENT_TIMESTAMP AS initialized_at) AS backfill_boundary
WHERE NOT EXISTS (
    SELECT 1
    FROM chat_rooms
    WHERE chat_rooms.room_id = rooms.id
);
