CREATE TABLE chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    purge_after TIMESTAMP WITH TIME ZONE,
    messages_purged_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_rooms_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE NO ACTION,
    CONSTRAINT uq_chat_rooms_room UNIQUE (room_id),
    CONSTRAINT ck_chat_rooms_purge_completion
        CHECK (messages_purged_at IS NULL OR purge_after IS NOT NULL)
);
