CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    client_message_id VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_messages_chat_room
        FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id) ON DELETE NO ACTION,
    CONSTRAINT fk_chat_messages_sender_user
        FOREIGN KEY (sender_user_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT uq_chat_messages_room_sender_client_message
        UNIQUE (chat_room_id, sender_user_id, client_message_id)
);

CREATE INDEX idx_chat_messages_room_id_desc
    ON chat_messages (chat_room_id, id DESC);
